# Generated by Django 5.2.11 on 2026-03-10 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_autor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='autor',
            old_name='descricao',
            new_name='email',
        ),
        migrations.AddField(
            model_name='autor',
            name='nome',
            field=models.CharField(default='Autor desconhecido', max_length=100),
            preserve_default=False,
        ),
    ]
