# Generated by Django 6.0.3 on 2026-03-10 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rename_descricao_autor_email_autor_nome'),
    ]

    operations = [
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('isbn', models.CharField(blank=True, max_length=32, null=True)),
                ('quantidade', models.CharField(blank=True, default=0, null=True)),
                ('preco', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
            ],
        ),
    ]
